site_name: SSP21-CPP
theme:
  name: 'material'  
  palette:
    primary: 'Blue Grey'
    accent: 'Green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/ssp21.png'    
markdown_extensions:
  - admonition
  - codehilite
plugins:
  - markdownextradata
extra_css:
- 'stylesheets/extra.css'
nav:
- Home: 'index.md'
- Building: 'build.md'
- API:
  - 'Introduction' : 'api/intro.md'
  - 'IExecutor' : 'api/executor.md'
  - 'Logging' : 'api/logging.md'
  - 'ICryptoBackend' : 'api/crypto.md'
  - 'Error Handling' : 'api/error_handling.md'
- Proxy:
  - 'Introduction' : 'proxy/intro.md'
extra:  
  base_doxygen_path: 'https://ssp21.github.io/ssp21-cpp/doxygen/development'