site_name: SSP21-CPP
theme:
  name: 'material'  
  palette:
    primary: 'Blue Grey'
    accent: 'Green'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/ssp21.png'    
markdown_extensions:
  - admonition
plugins:
  - markdownextradata
extra_css:
- 'stylesheets/extra.css'
nav:
- Home: 'index.md'
- Building: 'build.md'
- API:
  - 'Introduction' : 'api_intro.md'
extra:
  version: 'development'
  base_doc_path: 'https://ssp21.github.com'